apiVersion: v1
kind: Service
metadata:
  name: prometheus-ops-thanos-sidecar-svc
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: ops
spec:
  type: NodePort
  selector:
    prometheus: ops
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
      protocol: TCP
