apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    tier: ops
  name: ops-kubelet
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    metricRelabelings:
    - action: replace
      sourceLabels:
      - exported_namespace
      targetLabel: app_namespace
    - action: keep
      regex: ^(.*)$
      sourceLabels:
      - app_namespace
    - action: keep
      regex: container_(cpu|memory|network|spec)_.*
      sourceLabels:
      - __name__
    - action: labeldrop
      regex: ^id$
    path: /metrics/cadvisor
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
  targetLabels:
  - app.kubernetes.io/name
