apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: ops-node-exporter
  namespace: monitoring
spec:
  ports:
  - name: metric
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    k8s-app: node-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    tier: ops
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metric
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_endpoint_node_name
      targetLabel: node
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      k8s-app: node-exporter
  targetLabels:
  - tier
