apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    metricRelabelings:
    - action: keep
      regex: ^(.*)$
      sourceLabels:
      - exported_namespace
    - action: keep
      regex: kube_(pod|node)_.*
      sourceLabels:
      - __name__
    port: http-metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  targetLabels:
  - app.kubernetes.io/name