name: BuildDockerfile
on:
  workflow_dispatch:
    inputs:
      repo:
        description: ""
        required: true
        default: "Ascend/ascend-hccl-controller"
      ref:
        description: ""
        required: true
        default: "branch_v5.0.0-RC3"
      dockerfile:
        description: ""
        required: true
        default: "build/Dockerfile"
      image:
        description: ""
        required: true
        default: "registry.cn-hangzhou.aliyuncs.com/opshub/ascend-hccl-controller"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.IDOCKERHUB_USERNAME }}
          password: ${{ secrets.IDOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          repository: "${{ inputs.repo }}"
          ref: "${{ inputs.ref }}"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ inputs.image }}:${{ inputs.ref }}"
          file: "${{ inputs.dockerfile }}"
