name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Build and push Controller
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/hubimage/hubimage:latest
          file: Dockerfile

      - name: Push hubimage to aliyun
        run: |
          docker tag docker.io/hubimage/hubimage:latest registry.cn-hangzhou.aliyuncs.com/shaowenchen/hubimage:latest
          docker push registry.cn-hangzhou.aliyuncs.com/shaowenchen/hubimage:latest
