name: BuildDockerfile
on:
  workflow_dispatch:
    inputs:
      repo:
        description: ""
        required: true
        default: "fluid-cloudnative/fluid"
      ref:
        description: ""
        required: true
        default: "release-1.0"
      dockerfile:
        description: ""
        required: true
        default: "docker/Dockerfile.dataset"
      image:
        description: ""
        required: true
        default: "hubimage/fluidcloudnative-dataset-controller"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          repository: ${{inputs.repo}}
          ref: ${{inputs.ref}}
      - name: Build and push amd64
        run: |
          docker buildx build --push --platform=linux/amd64 -t ${{inputs.image}}:${{inputs.ref}}-amd64 -f ${{inputs.dockerfile}} .
      - name: Build and push arm64
        run: |
          docker buildx build --push --platform=linux/arm64 -t ${{inputs.image}}:${{inputs.ref}}-arm64 -f ${{inputs.dockerfile}} .
      - name: Manifest
        run: |
          docker manifest create ${{inputs.image}}:${{inputs.ref}} ${{inputs.image}}:${{inputs.ref}}-amd64 ${{inputs.image}}:${{inputs.ref}}-arm64
          docker manifest annotate ${{inputs.image}}:${{inputs.ref}} ${{inputs.image}}:${{inputs.ref}}-arm64 --arch arm64
          docker manifest annotate ${{inputs.image}}:${{inputs.ref}} ${{inputs.image}}:${{inputs.ref}}-amd64 --arch amd64
          docker manifest push ${{inputs.image}}:${{inputs.ref}}