name: CLI

on:
  push:
    paths:
      - "cli/**"
    branches:
      - main
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push git lfs
        uses: docker/build-push-action@v3
        with:
          push: true
          file: cli/Dockerfile.git
          tags: hubimage/cli-git:latest
      - name: Working
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: bash ./.github/workflows/copy.sh ./cli/images.yaml
