name: Demo

on:
  push:
    paths:
      - "demo/**"
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push alpine
        uses: docker/build-push-action@v3
        with:
          push: true
          file: demo/Dockerfile.alpine
          tags: hubimage/demo-alpine:latest
      - name: Build and push ubuntu
        uses: docker/build-push-action@v3
        with:
          push: true
          file: demo/Dockerfile.ubuntu
          tags: hubimage/demo-ubuntu:latest
      - name: Build and push fio
        uses: docker/build-push-action@v3
        with:
          push: true
          file: demo/Dockerfile.fio
          tags: hubimage/demo-fio:latest
      - name: Working
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: bash ./.github/workflows/copy.sh ./demo/images.yaml
