name: Demo

on:
  push:
    paths:
      - "demo/**"
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push nginx-vts
        uses: docker/build-push-action@v3
        with:
          push: true
          file: toolbox/alpine.Dockerfile
          tags: hubimage/toolbox-alpine:latest
      -
        name: Build and push toolbox
        uses: docker/build-push-action@v3
        with:
          push: true
          file: toolbox/ubuntu.Dockerfile
          tags: hubimage/toolbox-ubuntu:latest
      -
        name: Build and push toolbox
        uses: docker/build-push-action@v3
        with:
          push: true
          file: toolbox/fio.Dockerfile
          tags: hubimage/toolbox-fio:latest
