name: ManualCopyToACR

on:
  workflow_dispatch:
    inputs:
      src:
        description: ""
        required: true
        default: "volcanosh/vc-scheduler:v1.7.0"

      dest:
        description: ""
        required: true
        default: "registry.cn-hangzhou.aliyuncs.com/opshub/vc-scheduler:v1.7.0"
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Working
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          #!/bin/bash
          docker run --rm quay.io/skopeo/stable copy --multi-arch all --dest-username ${ACR_USERNAME} --dest-password ${ACR_PASSWORD} docker://${{github.event.inputs.src}} docker://${{github.event.inputs.dest}}
