name: ManualCopyTag

on:
  workflow_dispatch:
    inputs:
      src:
        description: ""
        required: true
        default: "docker.elastic.co/beats/metricbeat:8.3.2"
      dest:
        description: ""
        required: true
        default: "hubimage/elastic-metricbeat:8.3.2"
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Copy
        run: |
          docker pull ${{ inputs.src }}
          docker tag ${{ inputs.src }} ${{ inputs.dest }}
          docker push ${{ inputs.dest }}
