name: ManualCopy

on:
  workflow_dispatch:
    inputs:
      src:
        description: ""
        required: true
        default: "registry.k8s.io/kube-state-metrics/kube-state-metrics"
      dest:
        description: ""
        required: true
        default: "registry.cn-beijing.aliyuncs.com/opshub/registry-k8s-io-kube-state-metrics-kube-state-metrics"
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Generate images.yaml
        run: |
          echo ${{ inputs.src }}: ${{ inputs.dest }} >> ./manual-images.yaml
      - name: Working
        run: |
          cat ./manual-images.yaml
          bash ./.github/workflows/copy.sh ./manual-images.yaml
