name: ManualCopy

on:
  workflow_dispatch:
    inputs:
      src:
        description: ''
        required: true
        default: 'quay.io/cilium/operator-generic'
      dest:
        description: ''
        required: true
        default: 'hubimage/operator-generic'
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Generate images.yaml
        run: |
          echo ${{ inputs.src }}: ${{ inputs.dest }} >> ./manual-images.yaml
      - name: Working
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: bash ./.github/workflows/copy.sh ./manual-images.yaml