name: ManualCopy

on:
  workflow_dispatch:
    inputs:
      src:
        description: ""
        required: true
        default: "ghcr.io/kedacore/keda"
      dest:
        description: ""
        required: true
        default: "hubimage/ghcr-io-kedacore-keda"
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Working
        run: |
          tags=$(docker run --rm quay.io/skopeo/stable list-tags docker://${{ inputs.src }} | jq -r '.Tags[]')

          for tag in $tags; do
            echo "Copying ${{ inputs.src }}:$tag -> ${{ inputs.dest }}:$tag"
            docker run --rm -v ~/.docker/config.json:/auth.json quay.io/skopeo/stable copy --multi-arch all \
              docker://${{ inputs.src }}:$tag \
              docker://${{ inputs.dest }}:$tag \
              --dest-authfile /auth.json \
              --insecure-policy \
              --src-tls-verify=false \
              --dest-tls-verify=false \
              --retry-times 5
          done
