name: Observation

on:
  push:
    paths:
      - "observation/images-acr.yaml"
      - "observation/images.yaml"
    branches:
      - main
  schedule:
    - cron: "30 17 * * 3"
  workflow_dispatch:
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Working
        run: bash ./.github/workflows/copy.sh ./observation/images-acr.yaml
      - name: Working
        run: bash ./.github/workflows/copy.sh ./observation/images.yaml
