name: Runtime

on:
  push:
    paths:
      - "runtime/**"
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push ubuntu
        run: cd ./runtime/ubuntu && bash run.sh
      - name: Build and Push openjdk
        run: cd ./runtime/openjdk && bash run.sh