name: Storage-ACR2

on:
  push:
    branches:
      - main
    paths:
      - "storage/images-acr2.yaml"
  schedule:
    - cron: "0 18 * * 1"
  workflow_dispatch:
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Working
        run: bash ./.github/workflows/copy.sh ./storage/images-acr2.yaml
