name: Timer-ACR

on:
  push:
    paths:
      - "ai/images-acr.yaml"
    branches:
      - main
  schedule:
    - cron: "0 18,6 * * *"
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory to search for images.yaml and images-acr.yaml files (default: all directories)'
        required: false
        default: './'
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Working
        run: |
          SEARCH_DIR="${{ github.event.inputs.directory || './' }}"
          echo "Searching in directory: $SEARCH_DIR"
          
          find "$SEARCH_DIR" -type f -name "images.yaml" -exec bash ./.github/workflows/copy.sh {} \;
          find "$SEARCH_DIR" -type f -name "images-acr.yaml" -exec bash ./.github/workflows/copy.sh {} \;
